language: csharp
mono: none
sudo: required
dist: xenial
solution: "./src/NdArrayNet.sln"
dotnet: 2.2
script:
- dotnet restore ./src
- dotnet build ./src
- dotnet test ./src
env:
  global:
    secure: Dxi3z8iVkROySvWsdzLXuhNrIhJ6gggZLto+c+kV6rphaNvpSxXOQYgZ/Q9+KcmsfyM7caBr5f6arUaN/ceDyS08wo/bpq6c/702qthI6Ng9/e00ejupg/IASNRemegGjkSI2TzFSBQTbtQxVykJh25V17NH/WbCQVU8+5hPvVrtQnNmFqs4Uo7GHffHmkmbgpjid6JmhxNfewOUJRok0i6XY+Ew1SQhcjLXgshM1bLbJZld+Ne8HYyZTO0I2kLn9rtwKGx2sbsvTxRAvyNY8tTmjUPT8asd24EzqrTw7a1kUfsM7i0mX8xeQGt8vYZ5Wi5d8nuuw3+1dsa/6joNRElM+zUO0KNTg5jWlMczmVVsXJLH+ZbTNwdO3TlRqge8CfHj/cgMXWc6cD26TArSvDEiCbgajBjLbKf9dpgUVhwKE1DLj6Mk0ApefEk26AjT4VUNvg5BebNS26hFqup17ByNMAjf4SwVAy+//Gv/T5IISbqga4xG6MpjSur7Y3IJwdBN/h9ciGqx2KTSUj4STy3Sl7X1zKRDU5Tk+iah4leHpf3StKcZqehc/xjiXzTfd1QjwPY3tGnWchQEpjNQO1raUCO5LaNf2ZmNyzQ42i916o/KFvFz6vnte7dpvK8Wp3bohqOQaTGsx6lOJLkRJbi4UA+0Mj3blM+UktA7QFk=
addons:
  coverity_scan:
    project:
      name: normalform/ndarraynet
      description: Build submitted via Travis CI
    notification_email: kim.jaeho@gmail.com
    build_command_prepend: dotnet restore ./src/NdArrayNet.sln
    build_command: dotnet build ./src/NdArrayNet.sln
    branch_pattern: coverity-scan
