language: csharp
mono: none
sudo: required
dist: xenial
solution: "./src/NdArrayNet.sln"
dotnet: 2.2
script:
- dotnet restore ./src
- dotnet build ./src
- dotnet test ./src
env:
  global:
  - secure: KPlUz2j2rZRRTh1l8qWN61UmET30MKG+ljAhZUvIwsz1xbCZ8edYxphJS2npMtc5KQs7VEJeFkfIwT9y2gJFsBv1g7xEYyK3l/aQqsG7h+DaFPFt4vnesyTib8WjhUH215Eyff2MAc8Mq43fFTZNNTxA4/zPCyMv+9QNwLVZRYTXKRHNPN/ionXz+BAKcDaHqOBdODzfou+UsUIKJZKD1pAHLn3S2gNW1kXMRmUqeC+hlNV0/bzdsN7CfOwmfC9N+v5jx6GzQ2A1q1KgOeiYtjDxrVsEx514Ay+Vi9fB+8sYdT73arXo5CSX+6Uh+HdVctVNKo1N4Q1AN9q+HugvWy7WFKV7CgIqIYAUoRmvdkkAgBBkuJSZLecwVAbeKWM99ZMOoQT1onJ8kUUluaf92/LMisU63svoeDSuWZRYchPvjwu1QRPXZUqRbZNC56nDYB3gfZ8soNS+travh6vN0zeBeQ+cDmaYjRA39kWD4q25OnzHmxLNWoF1BwzMpxCRc5BgmXV725DH1qSL18KbbgycawF6xoyICOJFUqgcHRy6I9Oax6EhTEsjTHKiVAxTMdPTIcsdhWQEi61uYIP7wzyxJzmorUCSQc3RtTIIwI02vyOUwYQzs9HN4nvsg3Z5o2qzof1GzcuAKZEWuK22vQQNqHYitHUXzVYAo4SsmBM=
addons:
  coverity_scan:
    project:
      name: "normalform/ndarraynet"
      version: 0.1
      description: "Build submitted via Travis CI"
    notification_email: kim.jaeho@gmail.com
    build_command_prepend: "dotnet restore ./src/NdArrayNet.sln"
    build_command: "dotnet build ./src/NdArrayNet.sln"
    branch_pattern: coverity-scan
