language: csharp
mono: none
sudo: required
dist: xenial
solution: ./src/NdArrayNet.netcore.sln
dotnet: 2.2
script:
    - dotnet restore ./src/NdArrayNet.netcore.sln
    - dotnet build ./src/NdArrayNet.netcore.sln
    - dotnet test ./src/NdArrayNet.netcore.sln
