language: csharp
mono: none
sudo: required
dist: xenial
solution: "./src/NdArrayNet.sln"
dotnet: 2.2
script:
- dotnet restore ./src
- dotnet build ./src
- dotnet test ./src
env:
  global:
  - secure: H5XTtE+erPENGqz603UxmNOsT//JMhMCOGgs9eP9LqOaYm4CE2EhdMfK1TkgnKjarPL4AnOxgc/u+E6MV4vX7mI7rwBNPtxwOP8CyYpGXPp3Ou6s8dgx9WSNEq9Tp15WponEEa17OkVLSU8midfsSbDOTJU2NLsTe3Txf/YCcj46wQBOaA1lCBmwot0wrsgOtp8GjrPYjn8v4Siq8JNGh1kywlYUjhsO8sn4jkZv0DGiZ8u+Cv7XQZ6PwHYWi73h7ebYC4VE4zlRQzqCUezgWBGM7yxStfXl3Ynd688BW4tSTLLF0nFT5AldC2e9VmLDIhSlVmKk9yPjP7Ff2TwSIrEw1J1Sjiw5vEp0XquG4IdDI2nak+p2i0ORVDkd1ai2kbqTVdB0fjT25BCFgSRObK2Lkelv4ZbTS/DW0OIX/QTvXUCtw34gcPKw5PF/nUd5KkhNgEOVC6gN+1MycpOm4cMBuOAYNe1BUIaYiZcLYhNW3/+8gYWHeipHsiKoP+G9mCIb6X/IPzuushhGxMSF2JCZMJg5Yd6nXJbIliQvf72SLKHgNaO+91PDmi3F2fznIkm/+hTKFNYro55Py04ruyEdWerl/fOp/Sq7bOPmGzoLwRA4hV1uIQlogBsVQHy0bRq/BwVPgbxlnooDOlcj1JpSbUbmNfUszFOuhoVp90U=
addons:
  coverity_scan:
    project:
      name: normalform/ndarraynet
      description: Build submitted via Travis CI
    notification_email: kim.jaeho@gmail.com
    build_command_prepend: dotnet restore ./src/NdArrayNet.sln
    build_command: dotnet build ./src/NdArrayNet.sln
    branch_pattern: coverity-scan
