language: csharp
mono: none
sudo: required
dist: xenial
solution: "./src/NdArrayNet.sln"
dotnet: 2.2
script:
- dotnet restore ./src
- dotnet build ./src
- dotnet test ./src
env:
  global:
    secure: DUt4QupI2VE8vK8WoLHZyCNOLKNUNAkET91LIsUrxhoCTCWSsqhc/cnoXM14qn7cQUtiJXjVtJ4vgXmX+SDb8ji3qLiZsZLFYFSiA5unJBpfAxJ2pXcsqArug9XngSF5lzPuNtEONSTDBjW3vKbzxC2KQ0bbtDfQFT7CTn8HAfvBWMzTM0/c4bbuQbWpskzbnE4Pa210MDOZKSd+pK11HePPY0vXmCiwO2gNh+mk+OVyY1ZQA0o3e8uxAC2HJQN0MJK/arE2C1cgYbtnMCO918Ew7Jf41gx39KsPFI+CK6i4CrN+iS3kt7aVASJZbtZAaMCEfS2Is4DXY+vP/3k0A+x4QohKPrGrbh6Ce/Ef8szkVb5WxVTVqRQpaD3BVHemHgfsl84QJh+ZXviGeaSSmp75cVY3EKaMnYQACgzLz2S77yCdrUVcMQ/2F+7WXsss0OobgPJ9zUODnX/ErwEQRGRRCPWlGrVl6mt9ShoNG7XOrafsfNOjLtrdSfuh23npLmrKl06qMOpy8iKE51/a3Nkq655ZscKPOqAVnr0TR3Jw25OdsBeykVg5yWEndCJb4ZRoqQsRTLnozRP/nGf9PpPqDGbiQtuYF4Dk2bJfqTuuDMGPhHllOFFc68FX6Nsfu/xlwKQaE+VyQQ1fGJrZQpo4sSBqxY/SXgB5MZfS1aM=
addons:
  coverity_scan:
    project:
      name: normalform/ndarraynet
      description: Build submitted via Travis CI
    notification_email: kim.jaeho@gmail.com
    build_command_prepend: dotnet restore ./src/NdArrayNet.sln
    build_command: cov-build --dir cov-int dotnet build ./src/NdArrayNet.sln /t:Rebuild
    branch_pattern: coverity-scan
