language: csharp
mono: none
sudo: required
dist: xenial
solution: "./src/NdArrayNet.sln"
dotnet: 2.2
script:
- dotnet restore ./src
- dotnet build ./src
- dotnet test ./src
env:
  global:
  - secure: "P2FQ0jqF6ij4RdqyQ9ByiTHu1cD3nyZskUVefaZuI8XFw9pTsrPkGBlc6ukB+FlqSlQwKIRPptWNc1zVxTOpG6eQ6XPELBDDoK9htEma7NYOCUqjzBYElk6rqB+0FJq3m8bZHfoWTmo2AMllRPqQfcb/bnzU8sT20Xiw+g/GhqDwnf1imjiV0y5BASqCs9St/v8S7QhsqynAewRXaJi4yJP48FEpFbrOFHON3Zr/78YZRItqh5pISAPZHE/z0K2sN6mo82SEO41RpTbZ6/TBKuFHBNzvzYW7F/Xuz276OKR39l7D/bGikX+DwqY2B63cHTSK+elHtRMPuPzJVC2NujHSOG1MSGnVAGiaD8NIg8UcVOvCt+fPeRyCQCl0LFluem0jb3DtTkq4t78RelbyoB+OHmG6ztxONLKpJGSej7rO3LmihbUSswgsmXCi+Zqk+RjjAvB8ZMDwDLDCRUOMD9fZIvuDObd15F1cxf8rDEAUuW42pKr6hLjm70hHtO3pPyT7h6YsMXdBqArNn7ZN6EXzIfI1Erd99cDOIeQC/7IgEV3cjuHIXS2Bs8Y3HJop3R8t4bpU9U7e9tx9HrEk4dE7rc/D4SuwZ7bEealQRpS3ACAgoVaOnYvVIWWWaOtv3oGH/r4YHsiTqtYJFzZ+DHBThA1g2tOYSbuNpezFvg8="
addons:
  coverity_scan:
    project:
      name: "normalform/ndarraynet"
      description: "Build submitted via Travis CI
    notification_email: kim.jaeho@gmail.com
    build_command_prepend: "dotnet restore ./src/NdArrayNet.sln"
    build_command: "dotnet build ./src/NdArrayNet.sln"
    branch_pattern: "coverity-scan"
