version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    $opencover = (Resolve-Path "~\.nuget\packages\opencover\*\tools\OpenCover.Console.exe").ToString()

    Write-Host "opencover: $opencover"


    $testasm = (Resolve-Path "src\NdArrayNetUnitTest\bin\Debug\*\NdArrayNetUnitTest.dll


    & $opencover -register:user -target:vstest.console.exe -targetargs:"/logger:Appveyor $testasm" -output:".\coverage.xml" -filter:"+NdArrayNetUnitTest"


    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh

    bash codecov.sh -f "coverage.xml" -t 5fbd680d-dcc5-431e-bb0e-39ec47863522
