version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore ./src/NdArrayNet.netcore.sln
build:
  project: src/NdArrayNet.netcore.sln
  verbosity: minimal
test_script:
- ps: >-
    $opencover = (Resolve-Path "~\.nuget\packages\opencover\*\tools\OpenCover.Console.exe").ToString()

    Write-Host "Path of OpenCover: $opencover"

    dotnet test ./src/NdArrayNet.netcore.sln

    & $opencover -register:user -target:dotnet.exe -targetargs:"test ./src/NdArrayNet.netcore.sln" -output:"coverage.xml" -filter:"+NdArrayNetUnitTest" -oldstyle

    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh

    bash codecov.sh -f "coverage.xml" -t 5fbd680d-dcc5-431e-bb0e-39ec47863522
