version: 1.0.{build}
image: Visual Studio 2017
environment:
  CODECOV_TOKEN: 5fbd680d-dcc5-431e-bb0e-39ec47863522
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_test:
- ps: bash <(curl -s https://codecov.io/bash) -t 5fbd680d-dcc5-431e-bb0e-39ec47863522
